apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: mysql-pass
  literals:
    - databaseName=wordpress
    - username=wordpress-db-user
    - password=wordpress-db-passwd
- name: mysql-root-pass
  literals:
  - password=wordpress-db-rootpasswd
resources:
  - namespace.yaml
  - mysql-configmap.yaml
  - mysql-service.yaml
  - mysql-statefulset.yaml
  - wordpress-deployment.yaml
  - wordpress-ingress.yaml
  - wordpress-nfsserver.yaml
namespace: ${namespace}
