apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  tls:
  - secretName: mycert
  rules:
  - host: wordpress.myproject.com
    http:
      paths:
      - backend:
          service:
            name: wordpress-svc
            port:
              number: 8080
